import './globals.css'
import { Inter } from 'next/font/google'
// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css'
import SideBar from './components/sideBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  //const containerStyle={margin:5,padding:5,border:"solid",borderColor:"#ff0000"};
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className='row'>
          <div className='col-lg-9'>
            {children}
          </div>
          <div className='col-lg-3'>
            <SideBar/>
          </div>
          </div>
      </body>
    </html>
  )
}
